# cloudbuild.yaml
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        gcloud run deploy webhook-assistente \
          --project=$PROJECT_ID \
          --region=southamerica-east1 \
          --source . \
          --allow-unauthenticated \
          --set-secrets=OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest,WHATSAPP_TOKEN=WHATSAPP_TOKEN:latest,VERIFY_TOKEN=VERIFY_TOKEN:latest,META_APP_SECRET=META_APP_SECRET:latest,PHONE_NUMBER_ID=PHONE_NUMBER_ID:latest,WABA_ID=WABA_ID:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REFRESH_TOKEN=GOOGLE_REFRESH_TOKEN:latest

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DUMMY: "noop"
# Você pode definir PROJECT_ID/REGION/SERVICE como variáveis de ambiente do Trigger.
