# cloudbuild.yaml — build & deploy from source para Cloud Run
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        gcloud run deploy ${SERVICE} \
          --project=${PROJECT_ID} \
          --region=${REGION} \
          --source . \
          --allow-unauthenticated \
          --set-secrets=OPENROUTER_API_KEY=OPENROUTER_API_KEY:latest,WHATSAPP_TOKEN=WHATSAPP_TOKEN:latest,VERIFY_TOKEN=VERIFY_TOKEN:latest,META_APP_SECRET=META_APP_SECRET:latest
substitutions:
  _DUMMY: "noop"
# Você pode definir PROJECT_ID/REGION/SERVICE como variáveis de ambiente do Trigger.
